### PR TITLE
Added PrismJS formatting for blog markdown

### PR DESCRIPTION
**Pull request by MikeKingdom**
Currently it's using one of the built-in prism styles. We'll need change this once we have some idea on styling

### CODE REVIEW

**Comment by MikeKingdom** [comment]
It doesn't seem all that practical to use Grommet Markdown so you can pass what components to use for rendering. The prism plugin seems to just modify the 'html' property of the gatsby MarkdownRemark node. I think we can easily accomplish the styling with just a little CSS (ie. copy the theme and just tweak it as suggested by the plugin docs.)

I was considering overriding the anchor with a component that is smart about adding the right icon for various links like twitter, github etc. But wouldn't be able to do that with the CSS mechanism from what I can tell.

**Comment by karatechops** [comment]
We generally prefer a "Grommet" approach above using custom CSS to match HPE's theme. This is due to a multitude of reasons including - ensuring backward compatibility, fixing Grommet shortcomings, etc. @ericsoderberghp can help clarify why we choose a "Grommet" approach to technical executions if you have any questions. 

Let's explore maintaining the use of Grommet's components when rendering Markdown then adding code styling. The lib choice does not need to be Prism if it requires Remark.

**Comment by MikeKingdom** [comment]
I think the grommet approach I was using may be just fine if it can handle the highlighting of ```language another way.

**Comment by MikeKingdom** [comment]
Did this a different way that preserves the ability to use Grommet components

**Pull request closed without merging**
